name: absen_qr_3
description: "A new Flutter project."

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  google_fonts: ^6.3.2
  intl: ^0.20.2
  mobile_scanner: ^7.1.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#ffffff" # bisa diganti warna lain
  adaptive_icon_foreground: "assets/icon/logo.png"
